---
- name: Download alertmanager-irc-relay binary to local folder
  become: false
  get_url:
    url: "https://github.com/gouthamve/alertmanager-irc-relay/releases/download/v{{ alertmanager_irc_relay_version }}/alertmanager-irc-relay-{{ alertmanager_irc_relay_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    checksum: "sha256:{{ alertmanager_irc_relay_checksum }}"
  register: _download_binary
  until: _download_binary is success
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Unpack alertmanager-irc-relay binary
  become: false
  unarchive:
    src: "/tmp/alertmanager-irc-relay-{{ alertmanager_irc_relay_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/alertmanager-irc-relay-{{ alertmanager_irc_relay_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/alertmanager-irc-relay"
  delegate_to: localhost
  check_mode: false

- name: Propagate alertmanager-irc-relay binaries
  copy:
    src: "/tmp/alertmanager-irc-relay-{{ alertmanager_irc_relay_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/alertmanager-irc-relay"
    dest: "/usr/local/bin/alertmanager-irc-relay"
    mode: 0755
  notify:
    - restart alertmanager-irc-relay 

- name: Create configuration directory
  file:
    path: "/etc/alertmanager-irc-relay"
    state: directory
    owner: root
    group: root
    mode: 0755
