---
- include: preflight.yml
  tags:
    - alertmanager_irc_relay_install
    - alertmanager_irc_relay_configure
    - alertmanager_irc_relay_run

- include: install.yml
  become: true
  tags:
    - alertmanager_irc_relay_install

- include: configure.yml
  become: true
  tags:
    - alertmanager_irc_relay_configure

- name: Ensure alertmanager-irc-relay is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: alertmanager-irc-relay
    state: started
    enabled: true
  tags:
    - alertmanager_irc_relay_run
